# -*- coding: utf-8 -*-
"""Regresion_Lineal_calcio_2637.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTitPPE0Hpzh6gtTl9FfSjgY2Ap6mku8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Datos de la Serie A 2023–24
data = {
    'Equipo': ['Inter', 'Milan', 'Juventus', 'Atalanta', 'Bologna',
               'Roma', 'Lazio', 'Napoli', 'Fiorentina', 'Torino',
               'Monza', 'Genoa', 'Lecce', 'Udinese', 'Cagliari',
               'Empoli', 'Hellas Verona', 'Frosinone', 'Sassuolo', 'Salernitana'],
    'Goles': [89, 74, 68, 72, 65,
              60, 58, 77, 59, 46,
              45, 45, 32, 37, 42,
              29, 34, 35, 43, 32],
    'Tiros_por_partido': [15.6, 14.2, 13.1, 14.3, 13.5,
                          13.0, 12.8, 14.9, 13.2, 11.5,
                          10.9, 10.8, 9.5, 10.2, 9.8,
                          8.7, 9.0, 9.2, 10.0, 8.5],
    'Posesion': [57.3, 54.0, 52.5, 51.1, 50.8,
                 51.0, 50.5, 55.0, 49.8, 47.5,
                 47.0, 46.8, 44.5, 45.2, 44.0,
                 42.3, 43.0, 43.5, 44.7, 42.0],
    'Precision_pases': [87.8, 85.0, 84.5, 83.0, 82.5,
                        83.0, 82.0, 85.5, 81.5, 79.0,
                        78.5, 78.0, 76.0, 77.0, 75.5,
                        74.0, 74.5, 75.0, 76.5, 73.0],
    'Puntos': [88, 76, 72, 69, 68,
               63, 61, 70, 60, 53,
               52, 48, 38, 42, 40,
               36, 37, 35, 34, 31]
}

# Crear DataFrame
df = pd.DataFrame(data)

# Variables independientes (X) y dependiente (y)
X = df[['Goles', 'Tiros_por_partido', 'Posesion', 'Precision_pases']].values
y = df['Puntos'].values.reshape(-1, 1)

# Añadir columna de 1s para el término independiente
ones = np.ones((X.shape[0], 1))
X_aug = np.hstack([ones, X])

# Cálculo de los coeficientes mediante la fórmula de mínimos cuadrados
Xt = X_aug.T
XtX = Xt @ X_aug
XtX_inv = np.linalg.inv(XtX)
w = XtX_inv @ Xt @ y

# Mostrar coeficientes
coeficientes = pd.DataFrame(w, index=['Intercepto', 'Goles', 'Tiros_por_partido', 'Posesion', 'Precision_pases'], columns=['Coeficiente'])
print("Coeficientes del modelo:")
print(coeficientes)

# Predicción de puntos
y_pred = X_aug @ w
df['Puntos_Predichos'] = y_pred

# Comparación entre puntos reales y predichos
print("\nComparación entre puntos reales y predichos:")
print(df[['Equipo', 'Puntos', 'Puntos_Predichos']])

# Visualización
plt.figure(figsize=(12, 6))
plt.plot(df['Equipo'], df['Puntos'], marker='o', label='Puntos Reales')
plt.plot(df['Equipo'], df['Puntos_Predichos'], marker='x', linestyle='--', label='Puntos Predichos')
plt.title('Puntos Reales vs Predichos - Serie A 2023–24')
plt.xlabel('Equipo')
plt.ylabel('Puntos')
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
